<a href="https://colab.research.google.com/github/hasanahmad676/Big_Data_Lab/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# First one have to install numpy in his working directory by !pip install numpy  

In [ ]:
!pip install numpy

In [2]:
#here we will import numpy as np to work with numpy library as np
import numpy as np

we will create numpy array here

In [3]:
#HERE WE CREATE AN ONE DIMENSIONAL ARRAY
arr=np.array([12,13,14,15,16,17,18,19])

In [9]:
print(arr)                #print the array

[12 13 14 15 16 17 18 19]


In [5]:
type(arr)             #check tghe type of array

numpy.ndarray

In [10]:
arr.ndim         # check the dimension of the array

1

In [15]:
##HERE WE CREATE AN Two DIMENSIONAL ARRAY
arr1= np.array([[1,2,3],[4,5,6]])

In [16]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [17]:
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
array.ndim         # check the dimension of the array

2

In [ ]:
###HERE WE CREATE AN Three DIMENSIONAL ARRAY

In [18]:
arr2 = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])

In [19]:
print(arr2)

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


In [21]:
arr2.ndim          # check the dimension of the array

3

In [23]:
type(arr2)

numpy.ndarray

In [24]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)                                     #one can create an array as their wish by use ndmin
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [25]:
# dtype
np.array([1,2,3],dtype=float)     #one can create an array with their choose data type

array([1., 2., 3.])

In [26]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,11,2)          #it will create an array and print after 2 index

array([1, 3, 5, 7, 9])

In [28]:
# with reshape
np.arange(1,13).reshape(4,3)     # it will create an array as print with shape as you want

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [30]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
# np.random
np.random.random((3,4))

array([[0.80373002, 0.51842109, 0.31122462, 0.39152043],
       [0.70104263, 0.48811199, 0.12477416, 0.19748353],
       [0.7358728 , 0.83925587, 0.25554783, 0.16725799]])

In [33]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [34]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [36]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
# ndim
a2.ndim

2

In [38]:
# shape
print(a3.shape)                    #(2, 2, 2)  HERE FIRST INDEX DESCRIBE HOW MANY 2D ARRAYS IN THE ARRAY
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
# itemsize
a2.itemsize       # how memmory they took

8

In [41]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype

In [42]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [43]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

Array Operations

In [44]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
# scalar operations
a1                             #when you oprational work only one array its called scalar oparation


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
# arithmetic
a1 +2                # you can do all your arithmetic oparation

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [48]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [49]:
# vector operations
# arithmetic
a1 ** a2                              #when you oprational work only one array its called scalar oparation

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [55]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[66., 89., 53.],
       [81., 37., 39.],
       [54., 91., 45.]])

In [61]:
# max/min/sum/prod
# np.max(a1)
# np.min(a1)
# np.sum(a1)
np.prod(a1)

8046533573458380.0

In [66]:
# 0 -> col and 1 -> row
np.max(a1,axis=0)

array([81., 91., 53.])

In [67]:
# mean/median/std/var
np.var(a1,axis=1)

array([221.55555556, 411.55555556, 396.22222222])

In [68]:
# trigonomoetric functions
np.sin(a1)

array([[-0.02655115,  0.86006941,  0.39592515],
       [-0.62988799, -0.64353813,  0.96379539],
       [-0.55878905,  0.10598751,  0.85090352]])

In [69]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [70]:
# log and exponents
np.exp(a1)

array([[4.60718663e+28, 4.48961282e+38, 1.04137594e+23],
       [1.50609731e+35, 1.17191424e+16, 8.65934004e+16],
       [2.83075330e+23, 3.31740010e+39, 3.49342711e+19]])

In [71]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[51., 49., 84.],
       [ 1.,  9., 30.]])

Indexing and Slicing

In [74]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [75]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
#first---->raw  and second----->col
a2[1,0]

4

In [78]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
a3[1,0,0]

4

In [79]:
a3[1,0,1]

5

In [80]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [158]:
# Fancy Indexing

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [159]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[93, 76, 14, 82],
       [98, 76, 63, 92],
       [81, 97, 15, 34],
       [82, 48, 12, 79],
       [87, 64, 67, 41],
       [ 9, 48, 74, 77]])

In [160]:
# find all numbers greater than 50
a[a > 50]

array([93, 76, 82, 98, 76, 63, 92, 81, 97, 82, 79, 87, 64, 67, 74, 77])

In [161]:
# find out even numbers
a[a % 2 == 0]

array([76, 14, 82, 98, 76, 92, 34, 82, 48, 12, 64, 48, 74])

In [162]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([76, 82, 98, 76, 92, 82, 64, 74])

In [163]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([93, 76, 82, 76, 92, 81, 97, 15, 34, 82, 48, 12, 79, 87, 64, 67, 41,
        9, 48, 74])

In [82]:
a1[0:6]

array([0, 1, 2, 3, 4, 5])

In [83]:
a1[0:6:2]

array([0, 2, 4])

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a2[0] #indexing

array([0, 1, 2, 3])

In [89]:
a2[0,:]      #slicing

array([0, 1, 2, 3])

In [90]:
a2[:,2]

array([ 2,  6, 10])

In [92]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [94]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [96]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [103]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
a3[::2,::3,::2]

array([[[ 0,  2]],

       [[18, 20]]])

In [120]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

copy()vs view()

In [121]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)                   #the changes will not effect in orginal array
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [122]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
                                 #the changes will effect in orginal array
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Iterating

In [123]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [124]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [126]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [127]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [129]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [130]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [131]:
#Reshape

In [132]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [133]:
# ravel
a3.ravel()     #it convert all dimension into 1 dimension

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [134]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [135]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [136]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [138]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [146]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [151]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

speed

In [153]:
# numpy
import numpy as np
import time
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.0863499641418457


 memory

In [155]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [156]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

concatenate()

In [165]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [168]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


search

In [169]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)             # it gives the index number

print(x)

(array([3, 5, 6]),)


In [172]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)  #it use binary search

print(x)

3


In [173]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')
                                             # it began to search from right side
print(x)

2


sort

In [174]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [175]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [176]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
